FROM debian:bookworm-slim
ARG UID
ARG GID
RUN apt-get update && apt-get install -y inotify-tools git && rm -rf /var/lib/apt/lists/*
RUN groupadd scb -g$GID
RUN adduser --disabled-password --uid $UID --gid $GID --home /data --gecos "" scb
ADD entrypoints/scb.sh /scb.sh
RUN chmod +x /scb.sh
USER scb
WORKDIR /data
ENTRYPOINT ["/scb.sh"]
