FROM mcr.microsoft.com/dotnet/core/sdk:3.0.100 AS builder

ARG UID
ARG GID
RUN apt-get update && \
  apt-get install -y git && \
  rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/dgarage/NBXplorer.git
WORKDIR /NBXplorer
RUN ./build.sh

RUN groupadd nbx -g$GID
RUN adduser --disabled-password --uid $UID --gid $GID --home /data --gecos "" nbx
USER nbx

ENTRYPOINT ["ls"]
