#!/bin/bash
# Awning v2: Setup wizard
# 5-step guided setup for first-time installation

run_setup() {
    log_step "Awning v2 Setup Wizard"
    echo -e "This wizard will configure your Bitcoin + Lightning node.\n"

    step_prerequisites
    step_node_config
    step_scb_config
    step_generate_configs
    step_build_and_start
}

# ============================================================
# Step 1: Prerequisites
# ============================================================
step_prerequisites() {
    log_step "Step 1/5: Checking prerequisites"

    local missing=0

    for cmd in docker git openssl; do
        if check_command "$cmd"; then
            log_success "$cmd found"
        else
            missing=1
        fi
    done

    # Check docker compose plugin
    if docker compose version &>/dev/null 2>&1 || sudo docker compose version &>/dev/null 2>&1; then
        log_success "docker compose plugin found"
    else
        log_error "'docker compose' plugin is required (not docker-compose standalone)"
        missing=1
    fi

    # Check docker is running
    if docker info &>/dev/null 2>&1 || sudo docker info &>/dev/null 2>&1; then
        log_success "Docker daemon is running"
    else
        log_error "Docker daemon is not running"
        missing=1
    fi

    if [[ $missing -ne 0 ]]; then
        log_error "Please install missing prerequisites and re-run setup"
        exit 1
    fi

    echo ""
    log_success "All prerequisites met"
}

# ============================================================
# Step 2: Node configuration
# ============================================================
step_node_config() {
    log_step "Step 2/5: Node configuration"

    # Detect architecture
    local arch
    arch="$(uname -m)"
    local bitcoin_arch lnd_arch
    case "$arch" in
        x86_64)  bitcoin_arch="x86_64"; lnd_arch="amd64" ;;
        aarch64) bitcoin_arch="aarch64"; lnd_arch="arm64" ;;
        *)
            log_error "Unsupported architecture: $arch"
            exit 1
            ;;
    esac
    log_info "Detected architecture: ${arch} (Bitcoin: ${bitcoin_arch}, LND: ${lnd_arch})"

    # Node alias
    local node_alias
    node_alias="$(read_input "Node alias" "AwningNode")"

    # Versions
    local btc_version lnd_version electrs_version
    btc_version="$(read_input "Bitcoin Core version" "29.1")"
    lnd_version="$(read_input "LND version" "0.19.3-beta")"
    electrs_version="$(read_input "Electrs version" "0.10.10")"

    # LND wallet password
    echo ""
    log_info "Set your LND wallet password (min 8 characters)"
    log_info "This password unlocks your Lightning wallet on startup"
    local lnd_password lnd_password_confirm
    while true; do
        lnd_password="$(read_password "LND wallet password")"
        if ! validate_password "$lnd_password" 8; then
            continue
        fi
        lnd_password_confirm="$(read_password "Confirm password")"
        if [[ "$lnd_password" != "$lnd_password_confirm" ]]; then
            log_error "Passwords do not match"
            continue
        fi
        break
    done

    # Save to .env
    local env_file
    env_file="$(awning_path .env)"

    cat > "$env_file" <<EOF
# Awning v2 - Generated by setup wizard on $(date)
UID=$(id -u)
GID=$(id -g)
BITCOIN_ARCH=${bitcoin_arch}
LND_ARCH=${lnd_arch}
BITCOIN_CORE_VERSION=${btc_version}
LND_VERSION=${lnd_version}
ELECTRS_VERSION=${electrs_version}
NODE_ALIAS=${node_alias}
LND_PASSWORD=${lnd_password}
EOF

    # Store LND password for wallet auto-unlock
    mkdir -p "$(awning_path data/lnd)"
    echo "$lnd_password" > "$(awning_path data/lnd/password.txt)"

    log_success "Node configuration saved"
}

# ============================================================
# Step 3: SCB configuration
# ============================================================
step_scb_config() {
    log_step "Step 3/5: Static Channel Backup (SCB)"

    echo -e "SCB automatically backs up your Lightning channel state to GitHub."
    echo -e "You need a private GitHub repository and an SSH deploy key.\n"

    if confirm "Enable Static Channel Backup?" "y"; then
        local scb_repo
        scb_repo="$(read_input "GitHub SSH URL (e.g. git@github.com:user/lnd-backup.git)" "")"

        if [[ -z "$scb_repo" ]]; then
            log_warn "No repository provided, SCB will be disabled"
            echo "SCB_REPO=" >> "$(awning_path .env)"
        else
            echo "SCB_REPO=${scb_repo}" >> "$(awning_path .env)"
            log_success "SCB configured: ${scb_repo}"

            echo ""
            log_info "After setup completes, add the SCB SSH public key as a deploy key"
            log_info "in your GitHub repository (Settings > Deploy keys > Add deploy key)"
            log_info "The key will be displayed when the SCB container first starts."
        fi
    else
        echo "SCB_REPO=" >> "$(awning_path .env)"
        log_info "SCB disabled"
    fi
}

# ============================================================
# Step 4: Generate configs from templates
# ============================================================
step_generate_configs() {
    log_step "Step 4/5: Generating configuration files"

    # Generate random credentials
    local rpc_user rpc_password tor_password
    rpc_user="awning"
    rpc_password="$(generate_password 32)"
    tor_password="$(generate_password 32)"

    # Append to .env
    local env_file
    env_file="$(awning_path .env)"
    cat >> "$env_file" <<EOF
BITCOIN_RPC_USER=${rpc_user}
BITCOIN_RPC_PASSWORD=${rpc_password}
TOR_CONTROL_PASSWORD=${tor_password}
EOF

    # Generate Bitcoin rpcauth line using Python (same algorithm as Bitcoin Core's rpcauth.py)
    log_info "Generating Bitcoin RPC auth..."
    local rpcauth_line
    rpcauth_line="$(generate_rpcauth "$rpc_user" "$rpc_password")"

    # Generate Tor hashed password
    log_info "Generating Tor control password hash..."
    local tor_hashed
    tor_hashed="$(generate_tor_hash "$tor_password")"

    # Process templates
    local configs_dir
    configs_dir="$(awning_path configs)"

    # bitcoin.conf
    sed "s|{{BITCOIN_RPCAUTH}}|${rpcauth_line}|g" \
        "${configs_dir}/bitcoin.conf.template" > "${configs_dir}/bitcoin.conf"
    log_success "Generated bitcoin.conf"

    # lnd.conf
    sed -e "s|{{BITCOIN_RPC_USER}}|${rpc_user}|g" \
        -e "s|{{BITCOIN_RPC_PASSWORD}}|${rpc_password}|g" \
        -e "s|{{TOR_CONTROL_PASSWORD}}|${tor_password}|g" \
        "${configs_dir}/lnd.conf.template" > "${configs_dir}/lnd.conf"
    log_success "Generated lnd.conf"

    # electrs.toml
    sed -e "s|{{BITCOIN_RPC_USER}}|${rpc_user}|g" \
        -e "s|{{BITCOIN_RPC_PASSWORD}}|${rpc_password}|g" \
        "${configs_dir}/electrs.toml.template" > "${configs_dir}/electrs.toml"
    log_success "Generated electrs.toml"

    # torrc
    sed "s|{{TOR_HASHED_PASSWORD}}|${tor_hashed}|g" \
        "${configs_dir}/torrc.template" > "${configs_dir}/torrc"
    log_success "Generated torrc"

    # Create data directories with correct ownership
    for dir in bitcoin lnd electrs tor scb; do
        mkdir -p "$(awning_path "data/${dir}")"
    done

    log_success "All configuration files generated"
}

# Generate rpcauth line compatible with Bitcoin Core
# Uses the same HMAC-SHA256 algorithm as Bitcoin Core's rpcauth.py
generate_rpcauth() {
    local user="$1"
    local password="$2"

    # Generate 16 bytes of random salt (hex encoded = 32 chars)
    local salt
    salt="$(openssl rand -hex 16)"

    # HMAC-SHA256(salt, password)
    local hmac
    hmac="$(echo -n "${password}" | openssl dgst -sha256 -hmac "${salt}" -binary | xxd -p -c 256)"

    echo "rpcauth=${user}:${salt}\$${hmac}"
}

# Generate Tor hashed control password
# Format: 16:salt+hash (using S2K algorithm from Tor spec)
generate_tor_hash() {
    local password="$1"

    # Use Tor's own hashing if available in a temp container, otherwise use Python
    # The format is: "16:" + hex(salt) + hex(SHA1(salt + password))
    # with the S2K specifier byte
    local hash
    hash="$(python3 -c "
import hashlib, os, binascii
password = b'${password}'
# Indicator byte: 96 means 65536 iterations of SHA1
indicator = 96
count = (16 + (indicator & 15)) << ((indicator >> 4) + 6)
salt = os.urandom(8)
# S2K hash
data = salt + password
hash_input = b''
while len(hash_input) < count:
    hash_input += data
hash_input = hash_input[:count]
h = hashlib.sha1(hash_input).digest()
print('16:' + binascii.hexlify(salt).decode().upper() + '{:02X}'.format(indicator) + binascii.hexlify(h).decode().upper())
" 2>/dev/null)"

    if [[ -z "$hash" ]]; then
        log_error "Failed to generate Tor password hash (python3 required)"
        exit 1
    fi

    echo "$hash"
}

# ============================================================
# Step 5: Build and start
# ============================================================
step_build_and_start() {
    log_step "Step 5/5: Building and starting services"

    echo -e "This will build Docker images and start all services."
    echo -e "Building Electrs from source can take ${BOLD}up to 1 hour${NC} on ARM.\n"

    if ! confirm "Start building?" "y"; then
        echo ""
        log_info "You can build and start later with: ./awning.sh start"
        return 0
    fi

    echo ""
    dc_build
    echo ""
    dc_up
    echo ""

    log_success "All services started!"
    echo ""
    log_info "Monitor progress with: ./awning.sh logs"
    log_info "Check status with:     ./awning.sh status"
    echo ""
    log_info "Bitcoin Core will now sync the blockchain (this takes days)."
    log_info "Once synced, create your LND wallet with: ./awning.sh wallet-create"
}
